define(function(require) {
    'use strict';

    var $ = require('jquery'),
            _ = require('underscore'),
            Backbone = require('backbone');

    var resources = {
        /* app */
        'appTitleText': 'Network Operations Center | Telecom Station Entry Log',
        'loadingIconSrc': 'images/loading.gif',
        'logoImageSrc': 'images/aep_logo_180x180.png',
        'logoImageSvgSrc': 'images/aep_logo_180x180.svg',
        'logoImageAlt': 'AEP',
        'hazardIconSrc': 'images/hazard_180x180.png',
        'hazardIconSvgSrc': 'images/hazard_180x180.svg',
        'hazardIconAlt': 'hazard',
        'checkedInIconSrc': 'images/checked-in_180x180.png',
        'checkedInIconSvgSrc': 'images/checked-in_180x180.svg',
        'checkedInIconAlt': 'open check-in',
        /* header */
        'goToStationEntryLogListButtonText': 'Entry Log',
        'goToStationEntryLogHistoryListButtonText': 'History',
        'goToStationListButtonText': 'Stations',
        'goToPersonnelListButtonText': 'Personnel',
        'checkInButtonText': 'Check-in',
        'checkOutButtonText': 'Check-out',
        'extendDurationButtonText': 'Extend duration',
        'checkInSucessMessage': 'check-in succes',
        'checkInErrorMessage': 'check-in error',
        'checkOutSucessMessage': 'check-out succes',
        'checkOutErrorMessage': 'check-out error',
        /* station entry log list */
        'StationEntryLogListView.loadingMessage': 'loading station entries',
        'StationEntryLogListView.errorMessage': 'error',
        'StationEntryLogListView.infoMessage': 'info',
        'StationEntryLogListView.listViewTitleText': 'Open Station Entries',
        'StationEntryLogListView.refreshListButtonText': 'Refresh',
        'StationEntryLogListView.resetListOptionsButtonText': 'Reset',
        'StationEntryLogListView.newStationEntryLogButtonText': 'Create Manual Check-in',
        'StationEntryLogListView.statusFilterOpenOption': 'open',
        'StationEntryLogListView.statusFilterExpiredOption': 'expired',
        'StationEntryLogListView.regionFilterDefaultOption': '&#45;&#160;region&#160;&#45;',
        'StationEntryLogListView.areaFilterDefaultOption': '&#45;&#160;area&#160;&#45;',
        'StationEntryLogListView.updateListFilterButtonText': 'Update List',
        'StationEntryLogListView.stationNameHeaderText': 'Station',
        'StationEntryLogListView.personnelNameHeaderText': 'Personnel',
        'StationEntryLogListView.contactHeaderText': 'Contact',
        'StationEntryLogListView.inTimeHeaderText': 'Checked-In',
        'StationEntryLogListView.expectedOutTimeHeaderText': 'Est. Check-out',
        'StationEntryLogListView.purposeHeaderText': 'Purpose',
        'StationEntryLogListView.additionalInfoHeaderText': 'Additional Info',
        'StationEntryLogListView.regionHeaderText': 'Region',
        'StationEntryLogListView.areaHeaderText': 'Area',
        /* station entry log history list */
        'StationEntryLogHistoryListView.loadingMessage': 'loading station entries',
        'StationEntryLogHistoryListView.errorMessage': 'error',
        'StationEntryLogHistoryListView.infoMessage': 'info',
        'StationEntryLogHistoryListView.listViewTitleText': 'Historical Station Entry Log',
        'StationEntryLogHistoryListView.stationIdentifierFilterDefaultOption': '&#45;&#160;select&#160;&#45;',
        'StationEntryLogHistoryListView.regionFilterDefaultOption': '&#45;&#160;select&#160;&#45;',
        'StationEntryLogHistoryListView.areaFilterDefaultOption': '&#45;&#160;select&#160;&#45;',
        'StationEntryLogHistoryListView.refreshListButtonText': 'Refresh',
        'StationEntryLogHistoryListView.resetListOptionsButtonText': 'Reset',
        'StationEntryLogHistoryListView.stationNameHeaderText': 'Station',
        'StationEntryLogHistoryListView.personnelNameHeaderText': 'Personnel',
        'StationEntryLogHistoryListView.contactHeaderText': 'Contact',
        'StationEntryLogHistoryListView.inTimeHeaderText': 'Checked-In',
        'StationEntryLogHistoryListView.outTimeHeaderText': 'Checked-out',
        'StationEntryLogHistoryListView.purposeHeaderText': 'Purpose',
        'StationEntryLogHistoryListView.additionalInfoHeaderText': 'Additional Info',
        'StationEntryLogHistoryListView.regionHeaderText': 'Region',
        'StationEntryLogHistoryListView.areaHeaderText': 'Area',
        'StationEntryLogHistoryListView.startDateTimeHeaderText': 'Start Date/Time',
        'StationEntryLogHistoryListView.endDateTimeHeaderText': 'End Date/Time',
        /* station list */
        'StationListView.loadingMessage': 'loading stations',
        'StationListView.errorMessage': 'error',
        'StationListView.infoMessage': 'info',
        'StationListView.listViewTitleText': 'Stations',
        'StationListView.refreshListButtonText': 'Refresh',
        'StationListView.resetListOptionsButtonText': 'Reset',
        'StationListView.stationIdentifierSelectDefaultOption': '&#45;&#160;jump to station&#160;&#45;',
        'StationListView.regionFilterDefaultOption': '&#45;&#160;region&#160;&#45;',
        'StationListView.areaFilterDefaultOption': '&#45;&#160;area&#160;&#45;',
        'StationListView.stationNameHeaderText': 'Station',
        'StationListView.regionHeaderText': 'Region',
        'StationListView.areaHeaderText': 'Area',
        /* personnel list */
        'PersonnelListView.loadingMessage': 'loading',
        'PersonnelListView.errorMessage': 'error',
        'PersonnelListView.infoMessage': 'info',
        'PersonnelListView.listViewTitleText': 'Personnel',
        'PersonnelListView.listFilterHeaderText': 'Show Me',
        'PersonnelListView.personnelNameHeaderText': 'Personnel',
        'PersonnelListView.regionHeaderText': 'Region',
        'PersonnelListView.areaHeaderText': 'Area',
        /* station entry log */
        'StationEntryLogView.stationNameHeaderText': 'Station',
        'StationEntryLogView.personnelNameHeaderText': 'Personnel',
        'StationEntryLogView.contactHeaderText': 'Contact',
        'StationEntryLogView.inTimeHeaderText': 'Checked-In',
        'StationEntryLogView.outTimeHeaderText': 'Checked-out',
        'StationEntryLogView.durationHeaderText': 'Duration',
        'StationEntryLogView.purposeHeaderText': 'Purpose',
        'StationEntryLogView.additionalInfoHeaderText': 'Additional Info',
        'StationEntryLogView.regionHeaderText': 'Region',
        'StationEntryLogView.areaHeaderText': 'Area',
        /* station */
        'StationView.goToMapButtonText': 'View Station in Google Maps',
        'StationView.contactSectionTitleText': 'Contact Information',
        'StationView.locationSectionTitleText': 'Location Details',
        'StationView.emergencySectionTitleText': 'Medical Emergency Information',
        'StationView.otherSectionTitleText': 'Other Information',
        'StationView.faaSectionTitleText': 'FAA Information',
        'StationView.itfoSectionTitleText': 'IT FO Information',
        /* location */
        'StationView.audinetHeaderText': 'Audinet',
        'StationView.telephoneHeaderText': 'Telephone',
        'StationView.address1HeaderText': 'Street',
        'StationView.cityHeaderText': 'City',
        'StationView.stateHeaderText': 'State',
        'StationView.postalCodeHeaderText': 'Postal Code',
        'StationView.countyHeaderText': 'County',
        'StationView.latitudeHeaderText': 'Latitude',
        'StationView.longitudeHeaderText': 'Longitude',
        'StationView.directionsHeaderText': 'Directions',
        /* contact */
        'StationView.contactIdHeaderText': 'IT FO Contact',
        'StationView.contactPhoneHeaderText': 'Contact Phone',
        'StationView.contactSecurityPhoneHeaderText': 'Security Phone',
        'StationView.contactAddress1HeaderText': 'Mailing Address',
        'StationView.contactCityHeaderText': 'City',
        'StationView.contactStateHeaderText': 'State',
        'StationView.contactPostalCodeHeaderText': 'Postal Code',
        /* emergency */
        'StationView.medicalEmergencyDepartmentHeaderText': 'Medical Emergency',
        'StationView.medicalEmergencyDepartmentPhoneHeaderText': 'Medical Emergency Phone',
        'StationView.fireDepartmentHeaderText': 'Fire Department',
        'StationView.fireDepartmentPhoneHeaderText': 'Fire Department Phone',
        'StationView.policeDepartmentHeaderText': 'Police Department',
        'StationView.policeDepartmentPhoneHeaderText': 'Police Department Phone',
        /* other */
        'StationView.complexNameHeaderText': 'Complex',
        'StationView.owningOrganizationHeaderText': 'Owning Org.',
        'StationView.leasedCircuitsHeaderText': 'Leased Circuits',
        /* faa */
        'StationView.faaReportableHeaderText': 'FAA Reportable',
        'StationView.faaRegionHeaderText': 'FAA Region',
        'StationView.towerNumberHeaderText': 'Tower Number',
        'StationView.nearestAirportHeaderText': 'Nearest Airport',
        /* it fo */
        'StationView.benefittingOrganizationHeaderText': 'Benefitting Org.',
        'StationView.landOwnerHeaderText': 'Land Owner',
        'StationView.servingUtilityTelephoneHeaderText': 'Serving Utility Phone',
        'StationView.acCircuitFeederHeaderText': 'AC Circuit Feeder',
        'StationView.fuelProviderHeaderText': 'Fuel Provider',
        'StationView.areaHeaderText': 'IT FO Area',
        'StationView.regionHeaderText': 'IT FO Region',
        'StationView.equipmentHeaderText': 'Equipment',
        'StationView.telecomNpaHeaderText': 'Telecom NPA',
        'StationView.telecomNxxHeaderText': 'Telecom NXX',
        'StationView.servingElectricUtilityHeaderText': 'Serving Electric Utility',
        'StationView.servingTelephoneCompanyHeaderText': 'Serving Telephone Co.',
        'StationView.siteAccessMethodHeaderText': 'Site Access Method',
        'StationView.siteTypeHeaderText': 'Site Type',
        'StationView.notesHeaderText': 'Site Notes',
        'StationView.demarcationLocationHeaderText': 'Telco Demarc.',
        'StationView.transformerPoleHeaderText': 'Transformer Pole',
        /* new station entry log */
        'NewStationEntryLogView.viewTitleText': 'Manual Check-in',
        'NewStationEntryLogView.stationIdDefaultOption': '&#45;&#160;station&#160;&#45;',
        'NewStationEntryLogView.purposeDefaultOption': '&#45;&#160;purpose&#160;&#45;',
        'NewStationEntryLogView.durationDefaultOption': '&#45;&#160;duration&#160;&#45;',
        'NewStationEntryLogView.hasCrewYesOption': '&#45;&#160;yes&#160;&#45;',
        'NewStationEntryLogView.hasCrewNoOption': '&#45;&#160;no&#160;&#45;',
        'NewStationEntryLogView.stationIdHeaderText': 'Station Id',
        'NewStationEntryLogView.userIdHeaderText': 'User Id',
        'NewStationEntryLogView.firstNameHeaderText': 'First',
        'NewStationEntryLogView.middleInitialHeaderText': 'MI',
        'NewStationEntryLogView.lastNameHeaderText': 'Last',
        'NewStationEntryLogView.contactNumberHeaderText': 'Mobile&#160;&#35;',
        'NewStationEntryLogView.emailHeaderText': 'E-mail',
        'NewStationEntryLogView.purposeHeaderText': 'Purpose',
        'NewStationEntryLogView.durationHeaderText': 'Duration',
        'NewStationEntryLogView.expectedOutTimeHeaderText': 'Est. Check-out',
        'NewStationEntryLogView.purposeOtherHeaderText': 'Other',
        'NewStationEntryLogView.additionalInfoHeaderText': 'Additional Info',
        'NewStationEntryLogView.hasCrewHeaderText': 'Check-in With Crew?',
        'NewStationEntryLogView.saveButtonText': 'Save',
        'NewStationEntryLogView.cancelButtonText': 'Cancel',
        /* new station entry log */
        'EditStationEntryLogView.viewTitleText': 'Edit Check-in',
        'EditStationEntryLogView.stationIdDefaultOption': '&#45;&#160;station&#160;&#45;',
        'EditStationEntryLogView.purposeDefaultOption': '&#45;&#160;purpose&#160;&#45;',
        'EditStationEntryLogView.durationDefaultOption': '&#45;&#160;duration&#160;&#45;',
        'EditStationEntryLogView.hasCrewYesOption': '&#45;&#160;yes&#160;&#45;',
        'EditStationEntryLogView.hasCrewNoOption': '&#45;&#160;no&#160;&#45;',
        'EditStationEntryLogView.stationIdHeaderText': 'Station Id',
        'EditStationEntryLogView.userIdHeaderText': 'User Id',
        'EditStationEntryLogView.firstNameHeaderText': 'First',
        'EditStationEntryLogView.middleInitialHeaderText': 'MI',
        'EditStationEntryLogView.lastNameHeaderText': 'Last',
        'EditStationEntryLogView.contactNumberHeaderText': 'Mobile&#160;&#35;',
        'EditStationEntryLogView.emailHeaderText': 'E-mail',
        'EditStationEntryLogView.purposeHeaderText': 'Purpose',
        'EditStationEntryLogView.durationHeaderText': 'Duration',
        'EditStationEntryLogView.expectedOutTimeHeaderText': 'Est. Check-out',
        'EditStationEntryLogView.purposeOtherHeaderText': 'Other',
        'EditStationEntryLogView.additionalInfoHeaderText': 'Additional Info',
        'EditStationEntryLogView.hasCrewHeaderText': 'Check-in With Crew?',
        'EditStationEntryLogView.saveButtonText': 'Save',
        'EditStationEntryLogView.cancelButtonText': 'Cancel'
    };
    
    var defaultResource = '';

    var resourceHelpers = {
        getResource: function (key) {
            if (resources.hasOwnProperty(key)) {
                return resources[key];
            }
            return defaultResource;
        }
    };

    return resourceHelpers;
});